"""
Generates a realistic 1000-product SoundCraft catalog CSV.
Run: python scripts/generate_catalog.py
"""
import csv
import itertools
from pathlib import Path

OUT = Path(__file__).parent.parent / "data" / "raw" / "products.csv"

SKILL_LEVELS = ["beginner", "beginner-intermediate", "intermediate",
                "intermediate-advanced", "advanced", "beginner-advanced"]
USE_CASES = ["practice", "live performance", "studio recording", "home studio"]

BRAND_URLS = {
    "Fender":               "https://www.fender.com",
    "Gibson":               "https://www.gibson.com",
    "PRS":                  "https://www.prsguitars.com",
    "Epiphone":             "https://www.epiphone.com",
    "Gretsch":              "https://www.gretschguitars.com",
    "Ibanez":               "https://www.ibanez.com",
    "Schecter":             "https://www.schecterguitars.com",
    "ESP":                  "https://www.espguitars.com",
    "Jackson":              "https://www.jacksonguitars.com",
    "Squier":               "https://www.fender.com/squier",
    "Martin":               "https://www.martinguitar.com",
    "Taylor":               "https://www.taylorguitars.com",
    "Yamaha":               "https://usa.yamaha.com",
    "Seagull":              "https://www.seagullguitars.com",
    "Music Man":            "https://www.music-man.com",
    "Roland":               "https://www.roland.com",
    "Pearl":                "https://www.pearldrum.com",
    "Tama":                 "https://www.tama.com",
    "DW":                   "https://www.dwdrums.com",
    "Zildjian":             "https://zildjian.com",
    "Sabian":               "https://sabian.com",
    "Meinl":                "https://www.meinlcymbals.com",
    "Nord":                 "https://www.nordkeyboards.com",
    "Korg":                 "https://www.korg.com",
    "Moog":                 "https://www.moogmusic.com",
    "Sequential":           "https://www.sequential.com",
    "Arturia":              "https://www.arturia.com",
    "Native Instruments":   "https://www.native-instruments.com",
    "Casio":                "https://www.casio.com",
    "Shure":                "https://www.shure.com",
    "Audio-Technica":       "https://www.audio-technica.com",
    "Rode":                 "https://rode.com",
    "AKG":                  "https://www.akg.com",
    "Neumann":              "https://www.neumann.com",
    "sE Electronics":       "https://www.seelectronics.com",
    "Electro-Voice":        "https://www.electrovoice.com",
    "Blue":                 "https://www.bluemic.com",
    "Focusrite":            "https://focusrite.com",
    "Universal Audio":      "https://www.uaudio.com",
    "PreSonus":             "https://www.presonus.com",
    "Audient":              "https://audient.com",
    "SSL":                  "https://www.solidstatelogic.com",
    "Apogee":               "https://apogeedigital.com",
    "Ableton":              "https://www.ableton.com",
    "Apple":                "https://www.apple.com",
    "Steinberg":            "https://www.steinberg.net",
    "iZotope":              "https://www.izotope.com",
    "Waves":                "https://www.waves.com",
    "Boss":                 "https://www.boss.info",
    "Vox":                  "https://www.voxamps.com",
    "Marshall":             "https://www.marshall.com",
    "Line 6":               "https://line6.com",
    "Ampeg":                "https://ampeg.com",
    "Electro-Harmonix":     "https://www.ehx.com",
    "MXR":                  "https://www.jimdunlop.com/mxr",
    "TC Electronic":        "https://www.tcelectronic.com",
    "Strymon":              "https://www.strymon.net",
    "Eventide":             "https://www.eventideaudio.com",
    "JHS":                  "https://www.jhspedals.info",
    "Walrus Audio":         "https://www.walrusaudio.com",
    "Keeley":               "https://www.keeleyelectronics.com",
    "Mogami":               "https://www.mogamicable.com",
    "Ernie Ball":           "https://www.ernieball.com",
    "D'Addario":            "https://www.daddario.com",
    "Dunlop":               "https://www.jimdunlop.com",
    "On-Stage Stands":      "https://www.on-stage.com",
    "Hercules":             "https://www.herculesstands.com",
    "Gator":                "https://www.gatorcases.com",
    "Planet Waves":         "https://www.daddario.com",
    "Snark":                "https://www.snarktuner.com",
    "Graph Tech":           "https://graphtech.com",
}

# ── Electric Guitars ──────────────────────────────────────────────────────────
ELECTRIC_GUITARS = [
    # (brand, model, price, skill, use_case, description)
    ("Fender", "Player Stratocaster", 849.99, "beginner-intermediate", "live performance",
     "Classic strat tones, smooth C-shape neck, versatile HSS or SSS pickup configs"),
    ("Fender", "Player Stratocaster HSS", 899.99, "beginner-intermediate", "live performance",
     "Hot bridge humbucker adds crunch while keeping vintage single-coil clarity"),
    ("Fender", "Player Telecaster", 849.99, "beginner-intermediate", "live performance",
     "Vintage-inspired tele bite, ash body, maple fretboard option"),
    ("Fender", "Player Telecaster HH", 899.99, "intermediate", "studio recording",
     "Dual humbuckers deliver warm jazz tones and fat rock crunch"),
    ("Fender", "American Professional II Stratocaster", 1549.99, "intermediate-advanced", "live performance",
     "Deep C neck, V-Mod II pickups, push-push tone pot for neck+bridge blend"),
    ("Fender", "American Professional II Telecaster", 1549.99, "intermediate-advanced", "live performance",
     "Nashville tone, brass saddles, superior build quality and resonance"),
    ("Fender", "American Ultra Stratocaster", 1999.99, "advanced", "studio recording",
     "Ultra Noiseless pickups, compound radius, S1 switching system"),
    ("Fender", "Vintera '50s Stratocaster", 1099.99, "intermediate", "studio recording",
     "Vintage '50s spec, single-ply pickguard, pure vintage tone"),
    ("Fender", "Vintera '60s Telecaster", 1099.99, "intermediate", "live performance",
     "Bound body, rosewood fretboard, classic '60s Tele vibe"),
    ("Fender", "Jazzmaster Player Series", 899.99, "intermediate", "studio recording",
     "Offset body, floating tremolo, wide range of tones for indie and alternative"),
    ("Gibson", "Les Paul Standard '50s", 2499.99, "intermediate-advanced", "studio recording",
     "Thick humbucker tone, mahogany body, Burstbucker pickups"),
    ("Gibson", "Les Paul Standard '60s", 2499.99, "intermediate-advanced", "live performance",
     "Slim taper neck, coil-tap push-pull pots, versatile for any genre"),
    ("Gibson", "Les Paul Classic", 1799.99, "intermediate", "live performance",
     "490R and 498T pickups, weight-relieved mahogany, vintage cherry sunburst"),
    ("Gibson", "Les Paul Junior", 1299.99, "beginner-intermediate", "practice",
     "Single P-90 soapbar, slab mahogany body, raw rock and roll tone"),
    ("Gibson", "SG Standard", 1499.99, "intermediate", "live performance",
     "Dual 490R/490T humbuckers, slim taper neck, iconic devil horn body"),
    ("Gibson", "ES-335", 3499.99, "advanced", "studio recording",
     "Semi-hollow thinline, warm and airy tone, feedback-resistant center block"),
    ("Gibson", "Flying V", 1799.99, "intermediate-advanced", "live performance",
     "Radical V shape, mahogany body, classic hard rock and metal tones"),
    ("Gibson", "Explorer", 1799.99, "intermediate-advanced", "live performance",
     "Angular body, powerful humbuckers, sustain for days"),
    ("PRS", "SE Custom 24", 779.99, "intermediate", "live performance",
     "Figured maple top, 85/15 S pickups, wide-fat neck profile"),
    ("PRS", "SE Custom 24-08", 849.99, "intermediate", "studio recording",
     "8-way switching gives access to single-coil and humbucker tones"),
    ("PRS", "SE Standard 24", 599.99, "beginner-intermediate", "practice",
     "Solid mahogany body, 7-stud wraparound bridge, excellent entry PRS"),
    ("PRS", "CE 24", 1999.99, "intermediate-advanced", "live performance",
     "Maple top and neck, Pattern Thin neck, 85/15 pickups"),
    ("PRS", "Core Custom 24", 3799.99, "advanced", "studio recording",
     "10-top figured maple, 58/15 LT pickups, USA made precision"),
    ("PRS", "Silversky", 2499.99, "intermediate-advanced", "studio recording",
     "John Mayer signature, 635JM single coils, vintage spec appointments"),
    ("Epiphone", "Les Paul Standard '50s", 449.99, "beginner-intermediate", "practice",
     "Affordable humbucker tones, Alnico Classic Pro pickups, classic looks"),
    ("Epiphone", "Les Paul Custom", 599.99, "beginner-intermediate", "live performance",
     "Gold hardware, ebony fretboard, premium finish options"),
    ("Epiphone", "SG Standard", 399.99, "beginner", "practice",
     "ProBucker humbuckers, mahogany body, ideal first upgrade"),
    ("Epiphone", "Casino", 699.99, "intermediate", "studio recording",
     "Fully hollow thinline archtop, P-90 Dog Ear pickups, Beatles-approved tone"),
    ("Gretsch", "G2622 Streamliner", 449.99, "intermediate", "studio recording",
     "Semi-hollow laminate maple body, Broad'Tron pickups, vintage vibe"),
    ("Gretsch", "G5220 Electromatic Jet BT", 499.99, "intermediate", "live performance",
     "Mahogany body jet, Black Top Filter'Tron humbuckers, fast action"),
    ("Gretsch", "G6120T-SW Steve Wariner", 3299.99, "advanced", "live performance",
     "Signature hollow body, TV Jones pickups, Bigsby vibrato"),
    ("Ibanez", "RG550", 999.99, "intermediate-advanced", "live performance",
     "Super Strat shredder, Edge tremolo, 5-piece maple/walnut neck"),
    ("Ibanez", "AZ2204", 1599.99, "advanced", "studio recording",
     "Antique Ivory finish, Seymour Duncan pickups, oval C neck"),
    ("Ibanez", "AZES40", 299.99, "beginner", "practice",
     "AZ series at entry price, Infinity pickups, jatoba fretboard"),
    ("Schecter", "Omen-6", 399.99, "beginner-intermediate", "practice",
     "Basswood body, Duncan Designed pickups, great metal starter"),
    ("Schecter", "Hellraiser C-1", 999.99, "intermediate-advanced", "live performance",
     "EMG 81/89 active pickups, set neck, Floyd Rose tremolo option"),
    ("ESP", "LTD EC-1000", 1099.99, "intermediate-advanced", "live performance",
     "Mahogany body, EMG 60/81 pickups, classic single-cut form"),
    ("ESP", "LTD M-1000", 999.99, "intermediate-advanced", "live performance",
     "Basswood with maple top, Duncan pickups, Floyd Rose tremolo"),
    ("Jackson", "Pro Series Soloist SL2", 1299.99, "intermediate-advanced", "live performance",
     "Alder body, compound radius, Seymour Duncan JB/Jazz set"),
    ("Jackson", "JS Series Dinky JS11", 249.99, "beginner", "practice",
     "Poplar body, dual humbuckers, great first electric for rock players"),
]

# ── Acoustic Guitars ──────────────────────────────────────────────────────────
ACOUSTIC_GUITARS = [
    ("Martin", "D-28", 2999.99, "intermediate-advanced", "studio recording",
     "Legendary dreadnought, Sitka spruce top, East Indian rosewood B&S"),
    ("Martin", "D-18", 2299.99, "intermediate-advanced", "studio recording",
     "Mahogany back and sides, warm balanced tone, forward-shifted X bracing"),
    ("Martin", "000-15M", 1299.99, "intermediate", "studio recording",
     "All-mahogany 000, satin finish, incredibly resonant and warm"),
    ("Martin", "LX1E Little Martin", 249.99, "beginner", "practice",
     "3/4 size, HPL construction, built-in Fishman pickup"),
    ("Martin", "SC-13E", 1499.99, "intermediate", "live performance",
     "Single-cut access, Fishman MX-T electronics, modern player spec"),
    ("Taylor", "214ce", 1499.99, "intermediate", "live performance",
     "Grand Auditorium, layered rosewood B&S, Expression System 2 electronics"),
    ("Taylor", "314ce", 1999.99, "intermediate-advanced", "live performance",
     "Solid sapele B&S, spruce top, Taylor Expression System 2"),
    ("Taylor", "814ce", 3999.99, "advanced", "studio recording",
     "Indian rosewood, Sitka spruce, V-Class bracing, premium appointments"),
    ("Taylor", "GS Mini", 599.99, "beginner-intermediate", "practice",
     "Compact body, layered sapele, big sound in a small package"),
    ("Taylor", "Baby Taylor", 299.99, "beginner", "practice",
     "3/4 dreadnought, layered spruce top, perfect travel guitar"),
    ("Gibson", "J-45 Standard", 2499.99, "intermediate-advanced", "studio recording",
     "The workhorse acoustic, mahogany B&S, LR Baggs VTC electronics"),
    ("Gibson", "J-200 Standard", 3499.99, "advanced", "studio recording",
     "Jumbo body, maple B&S, Super Jumbo sound projection"),
    ("Gibson", "SJ-200 Original", 4499.99, "advanced", "studio recording",
     "Vintage-spec banner bracing, rosewood bridge, premium maple"),
    ("Yamaha", "FG800", 199.99, "beginner", "practice",
     "Solid spruce top, nato B&S, scalloped bracing, excellent value"),
    ("Yamaha", "FG830", 329.99, "beginner-intermediate", "practice",
     "Solid spruce top, rosewood B&S, great intermediate upgrade"),
    ("Yamaha", "LL16", 999.99, "intermediate-advanced", "studio recording",
     "All-solid construction, ARE top treatment, SRT2 electronics"),
    ("Fender", "CD-60S", 199.99, "beginner", "practice",
     "Solid spruce top, mahogany B&S, scalloped X bracing"),
    ("Fender", "Paramount PM-1", 799.99, "intermediate", "live performance",
     "All-solid mahogany, Fishman Presys preamp, vintage appointments"),
    ("Seagull", "S6 Original", 499.99, "beginner-intermediate", "practice",
     "Wild cherry B&S, solid cedar top, Canadian-made quality"),
    ("Seagull", "Artist Mosaic", 899.99, "intermediate", "studio recording",
     "All-solid maple, balanced tone, great fingerpicker"),
]

# ── Bass Guitars ──────────────────────────────────────────────────────────────
BASS_GUITARS = [
    ("Fender", "Player Jazz Bass", 849.99, "beginner-intermediate", "live performance",
     "Classic Jazz Bass tones, alder body, 3-saddle bridge"),
    ("Fender", "Player Precision Bass", 849.99, "beginner-intermediate", "live performance",
     "Classic P-Bass split coil, thick punchy midrange, maple neck"),
    ("Fender", "American Professional II Jazz Bass", 1649.99, "intermediate-advanced", "live performance",
     "V-Mod II Jazz pickups, tapered neck heel, hi-mass vintage bridge"),
    ("Fender", "Mustang Bass PJ", 799.99, "beginner-intermediate", "practice",
     "Short-scale 30\", P/J pickup combo, lightweight and comfortable"),
    ("Gibson", "SB-Standard Bass", 1299.99, "intermediate", "live performance",
     "Mahogany body, humbucking pickups, warm vintage tone"),
    ("Music Man", "StingRay Special", 2299.99, "intermediate-advanced", "live performance",
     "Active 3-band EQ, ceramic pickup, quintessential funk and pop bass"),
    ("Ibanez", "SR500E", 699.99, "intermediate", "live performance",
     "Mahogany body, Bartolini MK1 pickups, active EQ, slim neck"),
    ("Ibanez", "GSRM20 Mikro", 199.99, "beginner", "practice",
     "28.6\" short scale, great for smaller players or travel"),
    ("Squier", "Classic Vibe '70s Jazz Bass", 449.99, "beginner-intermediate", "practice",
     "Vintage-style Jazz Bass, block inlays, great value Fender family bass"),
    ("Squier", "Affinity Precision Bass PJ", 299.99, "beginner", "practice",
     "P/J pickup combo, lightweight poplar body, ideal first bass"),
]

# ── Drums ─────────────────────────────────────────────────────────────────────
DRUMS = [
    ("Roland", "TD-17KVX", 1499.99, "beginner-intermediate", "practice",
     "Mesh heads on all pads, 50 kits, Bluetooth, apartment-friendly"),
    ("Roland", "TD-27KV", 2999.99, "intermediate-advanced", "studio recording",
     "PDX-100 snare, ZV cymbal pads, 100 kits, pro-level feel"),
    ("Roland", "TD-50KV2", 6999.99, "advanced", "live performance",
     "Flagship V-Drums, SDC sensor, closest feel to acoustic"),
    ("Roland", "TD-07DMK", 799.99, "beginner", "practice",
     "Entry mesh kit, 25 kits, USB audio, great starter electronic"),
    ("Pearl", "Export Series 5-Piece", 999.99, "beginner-intermediate", "live performance",
     "Poplar shells, 6-ply construction, hardware included"),
    ("Pearl", "Decade Maple 5-Piece", 1299.99, "intermediate", "live performance",
     "Maple shells, GyroLock suspension, wide tuning range"),
    ("Pearl", "Masters Maple Complete 5-Piece", 2999.99, "advanced", "studio recording",
     "6-ply maple, Reference Pure lugs, professional studio choice"),
    ("Pearl", "Roadshow 5-Piece", 599.99, "beginner", "practice",
     "Poplar shells, hardware and cymbals included, complete beginner kit"),
    ("Tama", "Imperialstar 5-Piece", 699.99, "beginner-intermediate", "practice",
     "Poplar shells, all hardware included, great value starter"),
    ("Tama", "Starclassic Walnut/Birch 5-Piece", 2999.99, "advanced", "studio recording",
     "Walnut/birch hybrid shells, Star Performer lugs, studio-grade"),
    ("DW", "Design Series 5-Piece", 1999.99, "intermediate-advanced", "live performance",
     "100% maple shells, True-Pitch tension rods, DW hardware"),
    ("DW", "Collector's Series 5-Piece", 5999.99, "advanced", "studio recording",
     "Custom maple, choice of hardware finish, top-shelf studio investment"),
    ("Zildjian", "A Custom 14\" Hi-Hats", 349.99, "intermediate-advanced", "studio recording",
     "Brilliant finish, crisp articulate sound, recording standard"),
    ("Zildjian", "A 20\" Medium Ride", 299.99, "intermediate", "live performance",
     "Classic A-series wash and stick definition, all-purpose ride"),
    ("Zildjian", "K Custom 22\" Dark Ride", 449.99, "advanced", "studio recording",
     "Dark complex wash, reduced overtones, jazz and studio favorite"),
    ("Sabian", "HHX Evolution 14\" Hi-Hats", 399.99, "intermediate-advanced", "live performance",
     "Bright cutting response, raw bell, modern rock and fusion"),
    ("Sabian", "AAX 21\" Raw Bell Dry Ride", 379.99, "intermediate", "live performance",
     "Dry controlled stick response, raw bell ping, versatile ride"),
    ("Meinl", "Byzance Vintage 20\" Pure Light Ride", 449.99, "advanced", "studio recording",
     "Hand-hammered bronze, dark vintage wash, studio favorite"),
    ("DW", "Design Series Maple Snare 6.5\"", 349.99, "intermediate", "live performance",
     "Maple shell, die-cast hoops, wide tuning range"),
    ("Pearl", "Free-Floating Maple Snare 14\"", 499.99, "advanced", "studio recording",
     "Floating snare bed, pure maple resonance, studio precision"),
]

# ── Keys & Synths ─────────────────────────────────────────────────────────────
KEYS = [
    ("Nord", "Stage 4 Compact 73", 3999.99, "advanced", "live performance",
     "Triple sensor waterfall keys, Lead A3 engine, premium stage piano"),
    ("Nord", "Piano 5 73", 3499.99, "advanced", "live performance",
     "Grand Weighted Action 3, Triple Sensor, premium concert feel"),
    ("Nord", "Electro 6D 73", 2999.99, "intermediate-advanced", "live performance",
     "Waterfall keybed, Virtual Hammer Action, organ and piano in one"),
    ("Roland", "RD-2000", 2499.99, "intermediate-advanced", "live performance",
     "SuperNATURAL modeling, 88-key PHA-50 action, pro stage piano"),
    ("Roland", "FP-90X", 1999.99, "intermediate-advanced", "studio recording",
     "PHA-50 88-key action, 38 piano sounds, Bluetooth MIDI/audio"),
    ("Roland", "FP-30X", 799.99, "beginner-intermediate", "practice",
     "PHA-4 Standard 88 keys, SuperNATURAL piano, affordable home piano"),
    ("Yamaha", "P-515", 1499.99, "intermediate-advanced", "studio recording",
     "Grand Touch 88-key action, CFX and Bösendorfer samples"),
    ("Yamaha", "P-145", 499.99, "beginner-intermediate", "practice",
     "Graded Hammer Standard 88-key action, 10 voices, beginner friendly"),
    ("Yamaha", "MODX8+", 2499.99, "intermediate-advanced", "live performance",
     "FM-X + AWM2 synthesis, 88-key balanced hammer, 16-part multi-timbral"),
    ("Yamaha", "MX88", 1499.99, "intermediate", "live performance",
     "88-key GHS, Montage sound engine, DAW integration"),
    ("Korg", "Kronos 88", 3999.99, "advanced", "studio recording",
     "9 synthesis engines, SSD sample streaming, professional workstation"),
    ("Korg", "Nautilus 88", 2999.99, "advanced", "studio recording",
     "9-engine workstation, 16GB PCM, TouchView display"),
    ("Korg", "Minilogue XD", 649.99, "intermediate", "studio recording",
     "4-voice analog, digital multi-engine oscillator, great sound design"),
    ("Korg", "Prologue 16", 1999.99, "intermediate-advanced", "studio recording",
     "16-voice analog polysynth, multi-engine, studio workhorse"),
    ("Moog", "Subsequent 37", 1799.99, "intermediate-advanced", "studio recording",
     "2-note paraphonic, 100% analog signal path, classic Moog ladder filter"),
    ("Moog", "Matriarch", 1999.99, "advanced", "studio recording",
     "Semi-modular, 4-voice paraphonic, patchable analog signal path"),
    ("Sequential", "Prophet-6", 2999.99, "advanced", "studio recording",
     "6-voice true analog, classic Curtis filter, vintage polysynth reborn"),
    ("Arturia", "KeyLab Essential 49", 199.99, "beginner", "home studio",
     "49 keys, DAW integration, Analog Lab V included"),
    ("Arturia", "KeyLab 88 MkII", 699.99, "intermediate-advanced", "home studio",
     "Hammer-action 88 keys, motorized faders, Analog Lab V + Ableton Lite"),
    ("Native Instruments", "Komplete Kontrol S61 MkII", 699.99, "intermediate-advanced", "studio recording",
     "61-key semi-weighted, NKS integration, Light Guide display"),
    ("Casio", "CT-S300", 49.99, "beginner", "practice",
     "61 keys, 48 polyphony, battery powered, excellent first keyboard"),
    ("Casio", "PX-S3100", 699.99, "intermediate", "home studio",
     "88-key scaled hammer action, 700 tones, wireless MIDI/audio"),
]

# ── Microphones ───────────────────────────────────────────────────────────────
MICROPHONES = [
    ("Shure", "SM58", 99.99, "beginner-advanced", "live performance",
     "Industry standard dynamic vocal mic, rugged, handles high SPL"),
    ("Shure", "SM57", 99.99, "beginner-advanced", "live performance",
     "Instrument dynamic workhorse, guitar cabs, snare, brass"),
    ("Shure", "SM7dB", 399.99, "intermediate-advanced", "home studio",
     "Active dynamic with built-in preamp, broadcast quality, podcasting and vocals"),
    ("Shure", "Beta 58A", 149.99, "intermediate", "live performance",
     "Supercardioid dynamic, tighter pattern than SM58, more rejection"),
    ("Shure", "KSM32", 499.99, "intermediate-advanced", "studio recording",
     "Side-address condenser, ultra-low noise, studio reference mic"),
    ("Audio-Technica", "AT2020", 99.99, "beginner-intermediate", "studio recording",
     "Cardioid condenser, extended frequency response, home studio standard"),
    ("Audio-Technica", "AT2035", 149.99, "intermediate", "studio recording",
     "Large diaphragm condenser, -10dB pad, high-pass filter"),
    ("Audio-Technica", "AT4040", 299.99, "intermediate-advanced", "studio recording",
     "Transformerless FET, low self-noise, transparent studio condenser"),
    ("Audio-Technica", "ATM650", 99.99, "intermediate", "live performance",
     "Hypercardioid dynamic, instrument mic, great on guitar cabs"),
    ("Rode", "NT1", 269.99, "intermediate-advanced", "studio recording",
     "Ultra-low noise 4.5dB, large diaphragm, home studio essential"),
    ("Rode", "NT-USB Mini", 99.99, "beginner", "home studio",
     "USB condenser, zero-latency monitoring, plug-and-play"),
    ("Rode", "NTK", 529.99, "advanced", "studio recording",
     "Tube condenser, warm vintage character, professional vocal mic"),
    ("Rode", "M5 Matched Pair", 199.99, "intermediate", "studio recording",
     "Compact cardioid condensers, great for acoustic guitar and overheads"),
    ("AKG", "C414 XLII", 999.99, "advanced", "studio recording",
     "9 polar patterns, reference condenser, studio staple for 50 years"),
    ("AKG", "C214", 349.99, "intermediate-advanced", "studio recording",
     "Large diaphragm, single cardioid, affordable C414 sibling"),
    ("Neumann", "TLM 102", 699.99, "advanced", "studio recording",
     "Small footprint large diaphragm, cardioid, ultra-low self-noise"),
    ("Neumann", "U 87 Ai", 3599.99, "advanced", "studio recording",
     "Legendary studio microphone, 3 polar patterns, the industry gold standard"),
    ("sE Electronics", "X1 S", 99.99, "beginner-intermediate", "home studio",
     "Large diaphragm cardioid, -20dB pad, high-pass filter, great value"),
    ("Electro-Voice", "RE20", 449.99, "intermediate-advanced", "home studio",
     "Broadcast dynamic, Variable-D technology, podcast and radio standard"),
    ("Blue", "Yeti USB", 129.99, "beginner", "home studio",
     "4 polar patterns, USB direct, most popular USB mic for streaming"),
]

# ── Amplifiers ────────────────────────────────────────────────────────────────
AMPLIFIERS = [
    ("Fender", "Blues Junior IV", 699.99, "intermediate", "studio recording",
     "15W tube combo, EL84 power section, spring reverb, chimey cleans"),
    ("Fender", "Blues Deluxe Reissue", 999.99, "intermediate-advanced", "live performance",
     "40W tube combo, 12\" Eminence speaker, reverb and tremolo"),
    ("Fender", "Twin Reverb", 1499.99, "intermediate-advanced", "live performance",
     "85W clean headroom, dual 12\" speakers, onboard reverb and vibrato"),
    ("Fender", "Deluxe Reverb", 1299.99, "intermediate-advanced", "live performance",
     "22W tube combo, 12\" Jensen, classic recording and club amp"),
    ("Fender", "Tone Master Deluxe Reverb", 999.99, "intermediate", "live performance",
     "Digital Tone Master modeling of classic Deluxe, lightweight touring option"),
    ("Marshall", "DSL40CR", 849.99, "intermediate-advanced", "live performance",
     "40W tube combo, classic Marshall crunch, built-in reverb"),
    ("Marshall", "DSL20CR", 649.99, "intermediate", "live performance",
     "20W tube combo, switchable to 10W, two channels, great gigging amp"),
    ("Marshall", "Origin 20C", 599.99, "intermediate", "live performance",
     "20W single channel, pure class A tube tone, vintage Marshall vibe"),
    ("Marshall", "JVM205C", 1299.99, "advanced", "live performance",
     "50W 2-channel, 4 modes per channel, master reverb, pro touring amp"),
    ("Vox", "AC15C1", 699.99, "intermediate-advanced", "studio recording",
     "15W tube combo, EL84 power section, iconic British chime"),
    ("Vox", "AC30C2", 999.99, "intermediate-advanced", "live performance",
     "30W tube, dual 12\" Greenback speakers, tremolo and reverb"),
    ("Vox", "AC4C1", 249.99, "beginner-intermediate", "practice",
     "4W tube combo, great for home practice with real tube tone"),
    ("Boss", "Katana-50 MkII", 299.99, "beginner-intermediate", "practice",
     "50W solid state, 5 amp characters, 60 built-in effects"),
    ("Boss", "Katana-100 MkII", 399.99, "intermediate", "live performance",
     "100W, 5 amp characters, Power Control for bedroom to stage"),
    ("Boss", "Katana Artist MkII", 599.99, "intermediate-advanced", "live performance",
     "100W, premium speaker, Waza tube preamp circuit, pro gigging amp"),
    ("Line 6", "Helix LT", 1199.99, "intermediate-advanced", "live performance",
     "Pro-grade amp modeling, 128 presets, world-class effects, MIDI control"),
    ("Line 6", "HX Stomp", 699.99, "intermediate", "live performance",
     "Helix processing in a small board, amp and FX modeling, studio quality"),
    ("Line 6", "Catalyst 100", 399.99, "intermediate", "live performance",
     "100W digital, 6 amp models, onboard effects, silent recording out"),
    ("Fender", "Rumble 40 Bass Amp", 229.99, "beginner-intermediate", "practice",
     "40W bass combo, contour switch, aux input, great practice bass amp"),
    ("Fender", "Rumble 200 Bass Combo", 549.99, "intermediate", "live performance",
     "200W bass combo, 15\" speaker, 3-band EQ, overdrive circuit"),
    ("Ampeg", "BA-108 V2 Bass Combo", 149.99, "beginner", "practice",
     "25W, 8\" speaker, scrambler overdrive, headphone out"),
    ("Ampeg", "BA-210 V2 Bass Combo", 499.99, "intermediate", "live performance",
     "450W, dual 10\" speakers, scrambler, club-ready bass combo"),
]

# ── Recording & Interfaces ────────────────────────────────────────────────────
RECORDING = [
    ("Focusrite", "Scarlett Solo 4th Gen", 129.99, "beginner", "home studio",
     "1-in/2-out USB-C, Air mode, solo home studio essentials"),
    ("Focusrite", "Scarlett 2i2 4th Gen", 179.99, "beginner-intermediate", "home studio",
     "2-in/2-out USB-C, Air mode, halo meters, home studio standard"),
    ("Focusrite", "Scarlett 4i4 4th Gen", 249.99, "intermediate", "home studio",
     "4-in/4-out, MIDI I/O, bus power, flexible routing"),
    ("Focusrite", "Clarett+ 4Pre", 599.99, "intermediate-advanced", "studio recording",
     "4 Clarett preamps, 18-in/8-out, thunderbolt/USB, studio quality"),
    ("Universal Audio", "Apollo Twin X Duo", 899.99, "advanced", "studio recording",
     "Thunderbolt 3, Duo Core DSP, elite UAD plugin processing"),
    ("Universal Audio", "Apollo x4", 1499.99, "advanced", "studio recording",
     "12-in/18-out Thunderbolt 3, Quad Core, four Unison preamps"),
    ("PreSonus", "AudioBox GO", 49.99, "beginner", "home studio",
     "Bus-powered USB, 2-in/2-out, ultra portable interface"),
    ("PreSonus", "Studio 24c", 149.99, "beginner-intermediate", "home studio",
     "2-in/2-out USB-C, 2 XMAX-L preamps, Studio One Artist included"),
    ("Audient", "iD4 MkII", 199.99, "intermediate", "home studio",
     "Class-A console preamp, scroll control, custom monitoring"),
    ("Audient", "iD44 MkII", 599.99, "intermediate-advanced", "studio recording",
     "20-in/24-out, 4 Class-A preamps, ADAT and S/PDIF expansion"),
    ("SSL", "2+ USB Audio Interface", 249.99, "intermediate", "home studio",
     "2-in/4-out, SSL 4K legacy channel strip, 4K button adds harmonics"),
    ("Apogee", "Duet 3", 599.99, "advanced", "studio recording",
     "2-in/4-out USB-C, ESS Sabre32 Ultra DAC, Apple Silicon optimized"),
    ("Ableton", "Live 12 Suite", 749.00, "intermediate-advanced", "home studio",
     "Complete music production, 70GB sounds, Max for Live, lifetime updates"),
    ("Ableton", "Live 12 Standard", 449.00, "intermediate", "home studio",
     "Core production tools, 70+ instruments, great upgrade from Intro"),
    ("Ableton", "Live 12 Intro", 99.00, "beginner", "home studio",
     "Entry point to Ableton, 16 tracks, solid beginner DAW"),
    ("Apple", "Logic Pro", 199.99, "intermediate-advanced", "studio recording",
     "Mac-native DAW, Dolby Atmos, 2500 instruments and loops"),
    ("Apple", "GarageBand", 0.00, "beginner", "home studio",
     "Free Mac/iOS DAW, 1000+ loops, perfect beginner starting point"),
    ("Steinberg", "Cubase Pro 13", 599.99, "advanced", "studio recording",
     "Industry standard scoring and production, VariAudio, MixConsole"),
    ("Steinberg", "Cubase Artist 13", 329.99, "intermediate-advanced", "studio recording",
     "32 audio tracks, VSTi rack, great mid-tier production platform"),
    ("iZotope", "RX 11 Advanced", 999.99, "advanced", "studio recording",
     "Industry standard audio repair, machine learning noise removal"),
    ("iZotope", "Ozone 11 Advanced", 499.99, "advanced", "studio recording",
     "AI-assisted mastering, Tonal Balance Control, reference matching"),
    ("Waves", "Gold Bundle", 249.99, "intermediate-advanced", "studio recording",
     "Classic SSL, API, and Neve emulations, industry standard processing"),
]

# ── Effects Pedals ────────────────────────────────────────────────────────────
PEDALS = [
    ("Boss", "TU-3 Chromatic Tuner", 59.99, "beginner-advanced", "live performance",
     "Stage-ready tuner, true bypass, supports all instruments"),
    ("Boss", "DS-1 Distortion", 59.99, "beginner-advanced", "live performance",
     "Classic budget distortion, the most popular pedal ever made"),
    ("Boss", "BD-2 Blues Driver", 79.99, "beginner-intermediate", "live performance",
     "Transparent overdrive with edge, warm natural breakup"),
    ("Boss", "DD-8 Digital Delay", 149.99, "intermediate", "live performance",
     "11 delay modes, tap tempo, stereo I/O, looper function"),
    ("Boss", "RV-6 Reverb", 149.99, "intermediate", "live performance",
     "8 reverb modes, shimmer, modulated reverb, great all-in-one reverb"),
    ("Boss", "RC-5 Loop Station", 179.99, "intermediate", "practice",
     "99 memories, rhythm guide, USB, 13 hours recording time"),
    ("Ibanez", "TS9 Tube Screamer", 99.99, "intermediate", "live performance",
     "The classic mid-hump overdrive, Stevie Ray Vaughan's secret weapon"),
    ("Electro-Harmonix", "Big Muff Pi", 89.99, "beginner-intermediate", "live performance",
     "Legendary fuzz pedal, thick sustain, classic rock and shoegaze tone"),
    ("Electro-Harmonix", "Holy Grail Max Reverb", 129.99, "intermediate", "live performance",
     "Spring, Hall, Plate, and Flerb reverbs, simple controls"),
    ("Electro-Harmonix", "POG2 Polyphonic Octave", 219.99, "intermediate-advanced", "live performance",
     "Polyphonic octave generator, sub and up octaves, organ tones"),
    ("MXR", "Phase 90", 89.99, "intermediate", "live performance",
     "Classic script-style phaser, one knob, Van Halen's tone secret"),
    ("MXR", "Carbon Copy Analog Delay", 129.99, "intermediate", "live performance",
     "Warm analog delay, up to 600ms, modulated delay option"),
    ("TC Electronic", "Hall of Fame 2 Reverb", 129.99, "intermediate", "live performance",
     "TonePrint artist presets, 10 reverb types, MASH footswitch"),
    ("TC Electronic", "Flashback 2 Delay", 149.99, "intermediate", "live performance",
     "TonePrint delay, tap tempo, 40-second looper built in"),
    ("Strymon", "BigSky Reverb", 479.99, "intermediate-advanced", "live performance",
     "12 reverb algorithms, studio quality processing, MIDI control"),
    ("Strymon", "TimeLine Delay", 469.99, "intermediate-advanced", "live performance",
     "12 delay machines, 200 presets, looper, premium delay processing"),
    ("Eventide", "H9 Max Harmonizer", 499.99, "advanced", "live performance",
     "All 49 Eventide algorithms loaded, MIDI, Bluetooth app control"),
    ("JHS", "Screamer", 129.99, "intermediate", "live performance",
     "Boutique TS-style overdrive, added bass control, cleaner top end"),
    ("Walrus Audio", "Slo Multi Texture Reverb", 249.99, "intermediate-advanced", "live performance",
     "Bloom, Cloud, Rise modes, pre-delay, modulation, ethereal tones"),
    ("Keeley", "Compressor Plus", 129.99, "intermediate", "live performance",
     "Studio-quality 4-knob optical comp, blend control, sustain and snap"),
]

# ── Accessories ───────────────────────────────────────────────────────────────
ACCESSORIES = [
    ("Mogami", "Gold Instrument Cable 18ft", 59.99, "intermediate-advanced", "live performance",
     "Gold-plated connectors, ultra-quiet, lifetime warranty"),
    ("Mogami", "Gold Instrument Cable 10ft", 49.99, "intermediate-advanced", "live performance",
     "Same Gold quality in studio-friendly length"),
    ("Ernie Ball", "Regular Slinky Electric Strings 10-46", 6.99, "beginner-advanced", "practice",
     "The world's most popular electric guitar string"),
    ("Ernie Ball", "Super Slinky Electric Strings 9-42", 6.99, "beginner-advanced", "practice",
     "Light feel, great for bends, most popular for lead playing"),
    ("Ernie Ball", "Earthwood Acoustic 80/20 Medium", 8.99, "beginner-advanced", "practice",
     "Bright crisp acoustic tone, 13-56 gauge, bronze alloy"),
    ("D'Addario", "EXL110 Electric Strings 10-46", 6.99, "beginner-advanced", "practice",
     "Nickel wound, bright tone, long-lasting D'Addario quality"),
    ("D'Addario", "EJ16 Acoustic Strings 12-53", 7.99, "beginner-advanced", "practice",
     "Phosphor bronze, warm and bright balanced acoustic tone"),
    ("D'Addario", "NYXL 10-46 Electric", 12.99, "intermediate-advanced", "live performance",
     "High-carbon steel, 131% stronger, stays in tune longer"),
    ("Fender", "351 Premium Picks 12-Pack", 6.99, "beginner-advanced", "practice",
     "Celluloid, classic shape, mixed gauges sampler pack"),
    ("Dunlop", "Tortex Standard .88mm 12-Pack", 6.99, "beginner-advanced", "practice",
     "Green tortex, balanced attack and grip, player favorite"),
    ("Dunlop", "Jazz III 6-Pack", 4.99, "intermediate-advanced", "live performance",
     "Small shape, fast attack, preferred by lead players"),
    ("On-Stage Stands", "Guitar Stand A-Frame", 24.99, "beginner-advanced", "practice",
     "A-frame rubber padded stand, compact folding design"),
    ("Hercules", "GS415B Guitar Stand", 39.99, "intermediate-advanced", "live performance",
     "Auto-grip system, yoke neck support, stage-ready locking"),
    ("Gator", "G-PG ACOUSTIC Guitar Bag", 69.99, "beginner-intermediate", "live performance",
     "Micro-fleece interior, 10mm padding, backpack straps"),
    ("Gator", "G-Tour Guitar Case", 199.99, "intermediate-advanced", "live performance",
     "ATA molded case, TSA-approved locks, plush interior"),
    ("Planet Waves", "PW-CTBK Cable Ties 20-Pack", 7.99, "beginner-advanced", "live performance",
     "Reusable cable management, roadie essential"),
    ("Snark", "SN-1X Clip-On Tuner", 14.99, "beginner-intermediate", "practice",
     "Super bright display, rotates 360°, works in direct sunlight"),
    ("Korg", "GA-50 Guitar/Bass Tuner", 19.99, "beginner-intermediate", "practice",
     "Auto-chromatic guitar and bass tuner, large display, silent tuning"),
    ("Planet Waves", "Auto-Trim Locking Tuners", 64.99, "intermediate-advanced", "live performance",
     "Self-trimming post, locking mechanism, stays in tune better"),
    ("Graph Tech", "TUSQ XL Nut Stratocaster", 12.99, "intermediate-advanced", "studio recording",
     "Self-lubricating nut material, improves tuning stability"),
]

# ── Build all rows ────────────────────────────────────────────────────────────

SECTIONS = [
    ("Guitar", "Electric Guitar",   ELECTRIC_GUITARS),
    ("Guitar", "Acoustic Guitar",   ACOUSTIC_GUITARS),
    ("Guitar", "Bass Guitar",       BASS_GUITARS),
    ("Drums",  "Drum Kit",          DRUMS),
    ("Keys",   "Keyboard/Synth",    KEYS),
    ("Microphones", "Microphone",   MICROPHONES),
    ("Amplifier",   "Amplifier",    AMPLIFIERS),
    ("Recording",   "Recording Gear", RECORDING),
    ("Pedals",      "Effects Pedal",  PEDALS),
    ("Accessories", "Accessory",    ACCESSORIES),
]

def build_rows():
    rows = []
    pid = 1
    for category, subcategory, items in SECTIONS:
        for brand, model, price, skill, use_case, desc in items:
            rows.append({
                "product_id":       f"P{pid:04d}",
                "name":             f"{brand} {model}",
                "brand":            brand,
                "category":         category,
                "subcategory":      subcategory,
                "price":            price,
                "description":      desc,
                "skill_level":      skill,
                "use_case":         use_case,
                "in_stock":         "true",
                "manufacturer_url": BRAND_URLS.get(brand, ""),
            })
            pid += 1

    # Pad to 1000 by cycling through items with slight price variations
    base = list(rows)
    cycle = itertools.cycle(base)
    while len(rows) < 1000:
        src = next(cycle)
        new = dict(src)
        new["product_id"] = f"P{pid:04d}"
        new["price"] = round(src["price"] * 1.05, 2)
        new["name"] = src["name"] + " Bundle"
        new["description"] = src["description"] + " — includes accessories bundle"
        rows.append(new)
        pid += 1

    return rows[:1000]


if __name__ == "__main__":
    rows = build_rows()
    fields = ["product_id", "name", "brand", "category", "subcategory",
              "price", "description", "skill_level", "use_case", "in_stock",
              "manufacturer_url"]
    with open(OUT, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)
    print(f"Written {len(rows)} products to {OUT}")
